name: Build and Test

####################################################################################################
##  WORKFLOW TRIGGER
####################################################################################################
on: push
####################################################################################################
##  WORKFLOW JOBS
####################################################################################################
jobs:
  # Calls the shared build-and-test workflow.
  call_build_and_test:
    name: Call build-and-test workflow
    uses: RockLib/RockLib.Workflows/.github/workflows/build-and-test.yml@workflow-testing-without-publish
    secrets: inherit
